from __future__ import annotations

import math
import tempfile
from datetime import UTC, datetime
from pathlib import Path
from types import SimpleNamespace

import pytest

from app.evaluation.metrics import score_query
from app.evaluation.runner import EvaluationDataError, run_evaluation
from app.retrieval.bm25 import BM25Index
from app.retrieval.tokenizer import tokenize
from app.sources.openalex import OpenAlexMeta, OpenAlexPage, OpenAlexWork
from app.storage.repository import PaperStore


def test_tokenizer_handles_english_case_and_cjk_bigrams() -> None:
    assert tokenize("RAG检索系统") == ["rag", "检索", "索系", "系统"]


def test_bm25_ranks_matching_documents_and_breaks_ties_by_id() -> None:
    documents = [
        SimpleNamespace(openalex_id="W2", title="RAG retrieval", abstract=None),
        SimpleNamespace(openalex_id="W1", title="RAG retrieval", abstract=None),
        SimpleNamespace(openalex_id="W3", title="Graph neural networks", abstract=None),
    ]
    index = BM25Index(documents)

    hits = index.search("retrieval", limit=10)

    assert [hit.openalex_id for hit in hits] == ["W1", "W2"]
    assert hits[0].score == hits[1].score
    assert index.search(" ", limit=10) == []


def test_metric_values_for_graded_relevance_and_empty_ranking() -> None:
    metrics = score_query(["W2", "W1", "W3"], {"W1": 3, "W2": 1, "W3": 0}, cutoffs=(1, 3))

    assert metrics["hit@1"] == 1.0
    assert metrics["mrr@3"] == 1.0
    assert metrics["ndcg@3"] == pytest.approx((1 + 7 / math.log2(3)) / (7 + 1 / math.log2(3)))
    assert score_query([], {"W1": 2}, cutoffs=(1,))["ndcg@1"] == 0.0
    with pytest.raises(ValueError, match="non-negative"):
        score_query([], {"W1": -1})


def test_runner_uses_exact_frozen_snapshot_and_is_explicitly_exploratory() -> None:
    with tempfile.TemporaryDirectory(dir=Path(__file__).parent) as temp_dir:
        store = PaperStore(Path(temp_dir) / "catalog.sqlite3")
        page = OpenAlexPage(
            meta=OpenAlexMeta(count=2, page=1, per_page=2),
            results=[
                OpenAlexWork(
                    id="https://openalex.org/W100",
                    title="Retrieval quality in RAG",
                    abstract_inverted_index={"Retrieval": [0], "quality": [1], "RAG": [2]},
                ),
                OpenAlexWork(
                    id="https://openalex.org/W200",
                    title="Graph-based retrieval for language models",
                ),
            ],
            fetched_at=datetime(2026, 9, 23, tzinfo=UTC),
        )
        imported = store.import_openalex_page(page, query="retrieval", requested_page=1, per_page=2)
        papers = store.get_snapshot(imported.snapshot_id)["items"]
        expected_hashes = {item["openalex_id"]: item["payload_sha256"] for item in papers}
        dataset = {
            "dataset_id": "test",
            "dataset_version": 1,
            "judgment_status": "draft",
            "corpus": {
                "source": "openalex",
                "work_ids": list(expected_hashes),
                "content_sha256": expected_hashes,
            },
            "queries": [
                {"query_id": "Q1", "bucket": "test", "text": "retrieval RAG", "relevance": [2, 0]}
            ],
        }

        report = run_evaluation(store, dataset, "dataset-hash")
        changed = {
            **dataset,
            "corpus": {
                **dataset["corpus"],
                "content_sha256": {**expected_hashes, "W100": "0" * 64},
            },
        }

        assert report["corpus"]["snapshot_id"] == imported.snapshot_id
        assert report["dataset"]["exploratory_only"] is True
        assert (
            "qrels are provisional until reviewed by a human annotator"
            in report["dataset"]["limitations"]
        )
        assert report["summary"]["query_count"] == 1

        reviewed_report = run_evaluation(
            store, {**dataset, "judgment_status": "human_reviewed"}, "reviewed-hash"
        )
        assert reviewed_report["dataset"]["exploratory_only"] is True
        assert (
            "qrels are provisional until reviewed by a human annotator"
            not in reviewed_report["dataset"]["limitations"]
        )
        assistant_report = run_evaluation(
            store, {**dataset, "judgment_status": "assistant_labeled"}, "assistant-hash"
        )
        assert assistant_report["dataset"]["exploratory_only"] is True
        assert (
            "qrels were generated by an assistant and were not human-verified"
            in assistant_report["dataset"]["limitations"]
        )
        with pytest.raises(EvaluationDataError, match="exactly matches"):
            run_evaluation(store, changed, "dataset-hash")


def test_runner_rejects_partial_judgments() -> None:
    with tempfile.TemporaryDirectory(dir=Path(__file__).parent) as temp_dir:
        store = PaperStore(Path(temp_dir) / "empty.sqlite3")
        with pytest.raises(EvaluationDataError, match="work IDs"):
            run_evaluation(
                store,
                {"corpus": {"work_ids": ["W1"], "content_sha256": {}}, "queries": [{}]},
                "hash",
            )
