/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bootstrap */
        post: operations["bootstrap_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current */
        get: operations["get_current_session"];
        put?: never;
        post?: never;
        /** Remove */
        delete: operations["delete_current_session"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset */
        post: operations["reset_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Profile */
        post: operations["create_profile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Profile */
        patch: operations["patch_profile"];
        trace?: never;
    };
    "/api/v1/profiles/{profile_id}/revisions/{revision}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Revision */
        get: operations["get_profile_revision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/imports/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_manual_import"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage */
        post: operations["stage_manual_import"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/imports/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: operations["get_manual_import"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/imports/{job_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review */
        post: operations["review_manual_import"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/imports/{job_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish */
        post: operations["publish_manual_import"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Products */
        get: operations["list_catalog_products"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/products/{sku_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Product */
        get: operations["get_catalog_product"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/products/{sku_id}/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Offers */
        get: operations["list_catalog_offers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/price-quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quote */
        post: operations["quote_catalog_prices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["get_liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["get_readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Platform Status */
        get: operations["get_platform_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CatalogPage */
        CatalogPage: {
            /** Items */
            items: components["schemas"]["ProductSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Data Version */
            data_version?: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Empty Reason */
            empty_reason?: "no_published_catalog" | null;
        };
        /** DependencyChecks */
        DependencyChecks: {
            /**
             * Database
             * @enum {string}
             */
            database: "ready" | "unavailable" | "not_configured" | "migration_required";
            /**
             * Redis
             * @enum {string}
             */
            redis: "ready" | "unavailable" | "disabled";
        };
        /** EmptyRequest */
        EmptyRequest: Record<string, never>;
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details: {
                [key: string]: string;
            };
            /** Request Id */
            request_id: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** FactView */
        FactView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key */
            key: string;
            /** Description */
            description: string;
            /**
             * Value Type
             * @enum {string}
             */
            value_type: "text" | "integer" | "decimal" | "boolean";
            /** Value */
            value: string | number | boolean | null;
            /** Unit */
            unit: string;
            /** Raw Value */
            raw_value: string | null;
            /** Raw Unit */
            raw_unit: string | null;
            /** Missing Reason */
            missing_reason: ("not_collected" | "not_disclosed" | "conflicting" | "not_applicable") | null;
            /** Conditions */
            conditions: {
                [key: string]: unknown;
            };
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /** Valid To */
            valid_to: string | null;
            evidence: components["schemas"]["SourceReference"];
        };
        /** FieldOrigin */
        FieldOrigin: {
            /**
             * Origin
             * @enum {string}
             */
            origin: "explicit" | "default";
            /**
             * Source
             * @enum {string}
             */
            source: "form" | "system";
            /** Message Id */
            message_id?: null;
            /** Confirmed At */
            confirmed_at?: string | null;
        };
        /** ImportInput */
        ImportInput: {
            /**
             * Format Version
             * @default manual-v1
             * @constant
             */
            format_version: "manual-v1";
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** External Batch Id */
            external_batch_id: string;
            /**
             * Synthetic
             * @default false
             */
            synthetic: boolean;
            /** Rows */
            rows: components["schemas"]["ImportRow"][];
            /** Configurations */
            configurations?: {
                [key: string]: {
                    [key: string]: string;
                };
            };
        };
        /** ImportJob */
        ImportJob: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** External Batch Id */
            external_batch_id: string;
            /** Synthetic */
            synthetic: boolean;
            /** Content Hash */
            content_hash: string;
            /**
             * Status
             * @enum {string}
             */
            status: "invalid" | "staged" | "approved" | "rejected" | "published";
            /**
             * Checkpoint
             * @enum {string}
             */
            checkpoint: "validated" | "reviewed" | "published";
            preview: components["schemas"]["Preview"];
            /** Reviewer */
            reviewer: string | null;
            /** Review Note */
            review_note: string | null;
            /** Version Id */
            version_id: string | null;
        };
        /** ImportRow */
        ImportRow: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "brands" | "product_families" | "product_skus" | "product_aliases" | "sources" | "source_documents" | "evidence" | "evidence_skus" | "attribute_definitions" | "spec_facts" | "merchants" | "merchant_listings" | "offer_snapshots";
            /** Data */
            data: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** Issue */
        Issue: {
            /** Row */
            row?: number | null;
            /** Code */
            code: string;
            /**
             * Field
             * @default
             */
            field: string;
            /** Message */
            message: string;
            /**
             * Blocking
             * @default true
             */
            blocking: boolean;
        };
        JsonValue: unknown;
        /** LaptopConstraints */
        LaptopConstraints: {
            /** Max Weight G */
            max_weight_g?: number | null;
        };
        /** LiveResponse */
        LiveResponse: {
            /**
             * Status
             * @default alive
             * @constant
             */
            status: "alive";
        };
        /** OfferPage */
        OfferPage: {
            /** Items */
            items: components["schemas"]["OfferView"][];
            /** Data Version */
            data_version?: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Empty Reason */
            empty_reason?: ("no_published_catalog" | "no_matching_offers") | null;
        };
        /** OfferView */
        OfferView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Sku Id
             * Format: uuid
             */
            sku_id: string;
            /** Merchant Name */
            merchant_name: string;
            /** Platform */
            platform: string;
            /** Listing Url */
            listing_url: string;
            /** Amount Minor */
            amount_minor: number | null;
            /** Amount Missing Reason */
            amount_missing_reason: ("not_collected" | "not_disclosed" | "conflicting" | "not_applicable") | null;
            /** Shipping Minor */
            shipping_minor: number | null;
            /** Tax Minor */
            tax_minor: number | null;
            /** Tax Included */
            tax_included: boolean | null;
            /**
             * Currency
             * @constant
             */
            currency: "CNY";
            /** Region */
            region: string;
            /**
             * Stock Status
             * @enum {string}
             */
            stock_status: "in_stock" | "out_of_stock" | "preorder" | "unknown";
            /**
             * Condition
             * @enum {string}
             */
            condition: "new" | "used" | "refurbished" | "unknown";
            /**
             * Eligibility Type
             * @enum {string}
             */
            eligibility_type: "unconditional" | "member" | "coupon" | "bundle" | "unknown";
            /** Eligibility Details */
            eligibility_details: string | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Freshness
             * @enum {string}
             */
            freshness: "current" | "historical";
            evidence: components["schemas"]["SourceReference"];
            /**
             * Data Version
             * Format: uuid
             */
            data_version: string;
        };
        /** PCConstraints */
        PCConstraints: {
            /** Wifi Required */
            wifi_required?: boolean | null;
        };
        /** PatchRequest */
        PatchRequest: {
            /** Expected Revision */
            expected_revision: number;
            patch: components["schemas"]["ProfilePatch"];
        };
        /** PlatformStatus */
        PlatformStatus: {
            /**
             * Stage
             * @default catalog
             * @constant
             */
            stage: "catalog";
            /**
             * Data Status
             * @default empty
             * @enum {string}
             */
            data_status: "empty" | "published";
            /**
             * Recommendation Available
             * @default false
             * @constant
             */
            recommendation_available: false;
            /**
             * Mode
             * @default deterministic
             * @constant
             */
            mode: "deterministic";
            /**
             * Market
             * @default CN
             * @constant
             */
            market: "CN";
            /**
             * Currency
             * @default CNY
             * @constant
             */
            currency: "CNY";
            /** Data Version */
            data_version?: string | null;
        };
        /** Preview */
        Preview: {
            /** Content Hash */
            content_hash: string;
            /** Base Version */
            base_version: string | null;
            /** Rows */
            rows: components["schemas"]["RowPreview"][];
            /** Issues */
            issues: components["schemas"]["Issue"][];
            /** Valid */
            valid: boolean;
            /** Publishable */
            publishable: boolean;
            /** Normalized */
            normalized: components["schemas"]["ImportRow"][];
            /** Conflict Groups */
            conflict_groups: string[][];
        };
        /** PriceItemInput */
        PriceItemInput: {
            /**
             * Sku Id
             * Format: uuid
             */
            sku_id: string;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
            /** Offer Id */
            offer_id?: string | null;
        };
        /** PriceQuote */
        PriceQuote: {
            /** Data Version */
            data_version: string | null;
            /** Lines */
            lines: components["schemas"]["PricedLine"][];
            /** Known Subtotal Minor */
            known_subtotal_minor: number;
            /** Total Minor */
            total_minor: number | null;
            /** Price Complete */
            price_complete: boolean;
            /** Budget Minor */
            budget_minor: number | null;
            /** Budget Satisfied */
            budget_satisfied: boolean | null;
            /** Expires At */
            expires_at: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** PriceRequest */
        PriceRequest: {
            /**
             * Region
             * @default CN
             */
            region: string;
            /** Budget Minor */
            budget_minor?: number | null;
            /** Items */
            items: components["schemas"]["PriceItemInput"][];
        };
        /** PricedLine */
        PricedLine: {
            /**
             * Sku Id
             * Format: uuid
             */
            sku_id: string;
            /** Quantity */
            quantity: number;
            /** Offer Id */
            offer_id: string | null;
            /** Amount Minor */
            amount_minor: number | null;
            /** Shipping Minor */
            shipping_minor: number | null;
            /** Tax Minor */
            tax_minor: number | null;
            /** Tax Included */
            tax_included: boolean | null;
            /** Known Total Minor */
            known_total_minor: number;
            /** Unpriced Reasons */
            unpriced_reasons: ("NO_CURRENT_OFFER" | "PRICE_UNKNOWN" | "SHIPPING_UNKNOWN" | "TAX_UNKNOWN")[];
            /** Expires At */
            expires_at: string | null;
        };
        /** ProductDetail */
        ProductDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Record Key */
            record_key: string;
            /**
             * Category
             * @enum {string}
             */
            category: "cpu" | "gpu" | "motherboard" | "memory" | "ssd" | "psu" | "case" | "cooler" | "laptop";
            /** Region */
            region: string;
            /** Brand */
            brand: string;
            /** Family */
            family: string;
            /** Manufacturer Part Number */
            manufacturer_part_number: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "discontinued" | "unknown";
            /**
             * Data Version
             * Format: uuid
             */
            data_version: string;
            /** Missing Key Facts */
            missing_key_facts: boolean;
            /**
             * Identity Status
             * @enum {string}
             */
            identity_status: "pending" | "verified";
            /**
             * Revision Status
             * @enum {string}
             */
            revision_status: "unknown" | "known" | "not_applicable";
            /** Hardware Revision */
            hardware_revision: string | null;
            /** Configuration Fingerprint */
            configuration_fingerprint: string | null;
            /** Aliases */
            aliases: string[];
            /** Facts */
            facts: components["schemas"]["FactView"][];
        };
        /** ProductSummary */
        ProductSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Record Key */
            record_key: string;
            /**
             * Category
             * @enum {string}
             */
            category: "cpu" | "gpu" | "motherboard" | "memory" | "ssd" | "psu" | "case" | "cooler" | "laptop";
            /** Region */
            region: string;
            /** Brand */
            brand: string;
            /** Family */
            family: string;
            /** Manufacturer Part Number */
            manufacturer_part_number: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "discontinued" | "unknown";
            /**
             * Data Version
             * Format: uuid
             */
            data_version: string;
            /** Missing Key Facts */
            missing_key_facts: boolean;
        };
        /** ProfileInput */
        ProfileInput: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "pc" | "laptop" | "component";
            /** Budget Max Minor */
            budget_max_minor: number;
            /** Workloads */
            workloads: ("office" | "development" | "gaming" | "video" | "rendering" | "ai")[];
            /** Budget Scope */
            budget_scope: ("tower" | "laptop" | "component" | "monitor" | "peripherals" | "os" | "assembly" | "shipping")[];
            /**
             * Market
             * @default CN
             * @constant
             */
            market: "CN";
            /**
             * Currency
             * @default CNY
             * @constant
             */
            currency: "CNY";
            /** Excluded Brands */
            excluded_brands?: string[];
            pc_constraints?: components["schemas"]["PCConstraints"] | null;
            laptop_constraints?: components["schemas"]["LaptopConstraints"] | null;
            /** Component Category */
            component_category?: ("cpu" | "gpu" | "motherboard" | "memory" | "ssd" | "psu" | "case" | "cooler") | null;
        };
        /** ProfilePatch */
        ProfilePatch: {
            /** Mode */
            mode?: ("pc" | "laptop" | "component") | null;
            /** Budget Max Minor */
            budget_max_minor?: number | null;
            /** Workloads */
            workloads?: ("office" | "development" | "gaming" | "video" | "rendering" | "ai")[] | null;
            /** Budget Scope */
            budget_scope?: ("tower" | "laptop" | "component" | "monitor" | "peripherals" | "os" | "assembly" | "shipping")[] | null;
            /** Excluded Brands */
            excluded_brands?: string[] | null;
            pc_constraints?: components["schemas"]["PCConstraints"] | null;
            laptop_constraints?: components["schemas"]["LaptopConstraints"] | null;
            /** Component Category */
            component_category?: ("cpu" | "gpu" | "motherboard" | "memory" | "ssd" | "psu" | "case" | "cooler") | null;
        };
        /** ProfileSnapshot */
        ProfileSnapshot: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Revision */
            revision: number;
            profile: components["schemas"]["ProfileInput"];
            /** Origins */
            origins: {
                [key: string]: components["schemas"]["FieldOrigin"];
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PublishInput */
        PublishInput: {
            /** Content Hash */
            content_hash: string;
            /** Base Version */
            base_version: string | null;
        };
        /** Published */
        Published: {
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
            /** Synthetic */
            synthetic: boolean;
            /** Record Count */
            record_count: number;
        };
        /** ReadyResponse */
        ReadyResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
            checks: components["schemas"]["DependencyChecks"];
        };
        /** ReviewInput */
        ReviewInput: {
            /** Content Hash */
            content_hash: string;
            /** Base Version */
            base_version: string | null;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "reject";
            /** Note */
            note: string;
            /** Selected Fact Ids */
            selected_fact_ids?: string[];
        };
        /** RowPreview */
        RowPreview: {
            /** Row */
            row: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "brands" | "product_families" | "product_skus" | "product_aliases" | "sources" | "source_documents" | "evidence" | "evidence_skus" | "attribute_definitions" | "spec_facts" | "merchants" | "merchant_listings" | "offer_snapshots";
            /** Key */
            key: string;
            /**
             * Action
             * @enum {string}
             */
            action: "add" | "unchanged" | "invalid";
        };
        /** SessionResponse */
        SessionResponse: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Csrf Token */
            csrf_token: string;
            profile?: components["schemas"]["ProfileSnapshot"] | null;
        };
        /** SourceReference */
        SourceReference: {
            /** Source Name */
            source_name: string;
            /** Source Domain */
            source_domain: string;
            /** Document Title */
            document_title: string;
            /** Canonical Url */
            canonical_url: string;
            /** Document Hash */
            document_hash: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /**
             * Locator Kind
             * @enum {string}
             */
            locator_kind: "page" | "section" | "selector" | "json_pointer";
            /** Locator */
            locator: string;
            /** Excerpt Hash */
            excerpt_hash: string;
        };
        /** CatalogAlias */
        CatalogAlias: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Record Key */
            record_key: string;
            /**
             * Synthetic
             * @default false
             */
            synthetic: boolean;
            /**
             * Sku Id
             * Format: uuid
             */
            sku_id: string;
            /** Alias */
            alias: string;
            /** Normalized Alias */
            normalized_alias: string;
            /** Locale */
            locale: string;
        };
        /** CatalogAttribute */
        CatalogAttribute: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Record Key */
            record_key: string;
            /**
             * Synthetic
             * @default false
             */
            synthetic: boolean;
            /** Key */
            key: string;
            /**
             * Category
             * @enum {string}
             */
            category: "cpu" | "gpu" | "motherboard" | "memory" | "ssd" | "psu" | "case" | "cooler" | "laptop";
            /**
             * Value Type
             * @enum {string}
             */
            value_type: "text" | "integer" | "decimal" | "boolean";
            /** Canonical Unit */
            canonical_unit: string;
            /** Description */
            description: string;
        };
        /** CatalogBrand */
        CatalogBrand: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Record Key */
            record_key: string;
            /**
             * Synthetic
             * @default false
             */
            synthetic: boolean;
            /** Name */
            name: string;
            /** Normalized Name */
            normalized_name: string;
        };
        /** CatalogDocument */
        CatalogDocument: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Record Key */
            record_key: string;
            /**
             * Synthetic
             * @default false
             */
            synthetic: boolean;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Canonical Url */
            canonical_url: string;
            /** Title */
            title: string;
            /** Content Sha256 */
            content_sha256: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /**
             * Published At
             * @default null
             */
            published_at: string | null;
            /** Parser Version */
            parser_version: string;
            /**
             * Storage Key
             * @default null
             */
            storage_key: string | null;
        };
        /** CatalogEvidence */
        CatalogEvidence: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Record Key */
            record_key: string;
            /**
             * Synthetic
             * @default false
             */
            synthetic: boolean;
            /**
             * Review Status
             * @default pending
             * @enum {string}
             */
            review_status: "pending" | "approved" | "rejected";
            /**
             * Reviewer
             * @default null
             */
            reviewer: string | null;
            /**
             * Reviewed At
             * @default null
             */
            reviewed_at: string | null;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Locator Kind
             * @enum {string}
             */
            locator_kind: "page" | "section" | "selector" | "json_pointer";
            /** Locator */
            locator: string;
            /** Excerpt Sha256 */
            excerpt_sha256: string;
        };
        /** CatalogEvidenceScope */
        CatalogEvidenceScope: {
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            /**
             * Sku Id
             * Format: uuid
             */
            sku_id: string;
            /** Synthetic */
            synthetic: boolean;
        };
        /** CatalogFact */
        CatalogFact: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Record Key */
            record_key: string;
            /**
             * Synthetic
             * @default false
             */
            synthetic: boolean;
            /**
             * Review Status
             * @default pending
             * @enum {string}
             */
            review_status: "pending" | "approved" | "rejected";
            /**
             * Reviewer
             * @default null
             */
            reviewer: string | null;
            /**
             * Reviewed At
             * @default null
             */
            reviewed_at: string | null;
            /**
             * Sku Id
             * Format: uuid
             */
            sku_id: string;
            /**
             * Attribute Id
             * Format: uuid
             */
            attribute_id: string;
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            /**
             * Category
             * @enum {string}
             */
            category: "cpu" | "gpu" | "motherboard" | "memory" | "ssd" | "psu" | "case" | "cooler" | "laptop";
            /**
             * Value Type
             * @enum {string}
             */
            value_type: "text" | "integer" | "decimal" | "boolean";
            /** Unit */
            unit: string;
            /**
             * Value Text
             * @default null
             */
            value_text: string | null;
            /**
             * Value Integer
             * @default null
             */
            value_integer: number | null;
            /**
             * Value Decimal
             * @default null
             */
            value_decimal: number | string | null;
            /**
             * Value Boolean
             * @default null
             */
            value_boolean: boolean | null;
            /**
             * Missing Reason
             * @default null
             */
            missing_reason: ("not_collected" | "not_disclosed" | "conflicting" | "not_applicable") | null;
            /**
             * Raw Value
             * @default null
             */
            raw_value: string | null;
            /**
             * Raw Unit
             * @default null
             */
            raw_unit: string | null;
            /** Conditions */
            conditions?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /**
             * Valid To
             * @default null
             */
            valid_to: string | null;
        };
        /** CatalogFamily */
        CatalogFamily: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Record Key */
            record_key: string;
            /**
             * Synthetic
             * @default false
             */
            synthetic: boolean;
            /**
             * Brand Id
             * Format: uuid
             */
            brand_id: string;
            /**
             * Category
             * @enum {string}
             */
            category: "cpu" | "gpu" | "motherboard" | "memory" | "ssd" | "psu" | "case" | "cooler" | "laptop";
            /** Name */
            name: string;
        };
        /** CatalogListing */
        CatalogListing: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Record Key */
            record_key: string;
            /**
             * Synthetic
             * @default false
             */
            synthetic: boolean;
            /**
             * Merchant Id
             * Format: uuid
             */
            merchant_id: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** External Listing Id */
            external_listing_id: string;
            /** Listing Url */
            listing_url: string;
            /**
             * Matched Sku Id
             * @default null
             */
            matched_sku_id: string | null;
            /**
             * Match Evidence Id
             * @default null
             */
            match_evidence_id: string | null;
            /**
             * Match Status
             * @default pending
             * @enum {string}
             */
            match_status: "pending" | "matched" | "ambiguous" | "rejected";
        };
        /** CatalogMerchant */
        CatalogMerchant: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Record Key */
            record_key: string;
            /**
             * Synthetic
             * @default false
             */
            synthetic: boolean;
            /** Name */
            name: string;
            /** Platform */
            platform: string;
            /** External Seller Id */
            external_seller_id: string;
        };
        /** CatalogOffer */
        CatalogOffer: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Record Key */
            record_key: string;
            /**
             * Synthetic
             * @default false
             */
            synthetic: boolean;
            /**
             * Review Status
             * @default pending
             * @enum {string}
             */
            review_status: "pending" | "approved" | "rejected";
            /**
             * Reviewer
             * @default null
             */
            reviewer: string | null;
            /**
             * Reviewed At
             * @default null
             */
            reviewed_at: string | null;
            /**
             * Listing Id
             * Format: uuid
             */
            listing_id: string;
            /**
             * Sku Id
             * Format: uuid
             */
            sku_id: string;
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            /**
             * Amount Minor
             * @default null
             */
            amount_minor: number | null;
            /**
             * Amount Missing Reason
             * @default null
             */
            amount_missing_reason: ("not_collected" | "not_disclosed" | "conflicting" | "not_applicable") | null;
            /**
             * Shipping Minor
             * @default null
             */
            shipping_minor: number | null;
            /**
             * Tax Minor
             * @default null
             */
            tax_minor: number | null;
            /**
             * Tax Included
             * @default null
             */
            tax_included: boolean | null;
            /** Currency */
            currency: string;
            /** Region */
            region: string;
            /**
             * Stock Status
             * @default unknown
             * @enum {string}
             */
            stock_status: "in_stock" | "out_of_stock" | "preorder" | "unknown";
            /**
             * Condition
             * @default unknown
             * @enum {string}
             */
            condition: "new" | "used" | "refurbished" | "unknown";
            /**
             * Eligibility Type
             * @default unknown
             * @enum {string}
             */
            eligibility_type: "unconditional" | "member" | "coupon" | "bundle" | "unknown";
            /**
             * Eligibility Details
             * @default null
             */
            eligibility_details: string | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** CatalogSKU */
        CatalogSKU: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Record Key */
            record_key: string;
            /**
             * Synthetic
             * @default false
             */
            synthetic: boolean;
            /**
             * Family Id
             * Format: uuid
             */
            family_id: string;
            /**
             * Brand Id
             * Format: uuid
             */
            brand_id: string;
            /**
             * Category
             * @enum {string}
             */
            category: "cpu" | "gpu" | "motherboard" | "memory" | "ssd" | "psu" | "case" | "cooler" | "laptop";
            /**
             * Manufacturer Part Number
             * @default null
             */
            manufacturer_part_number: string | null;
            /**
             * Normalized Part Number
             * @default null
             */
            normalized_part_number: string | null;
            /** Region */
            region: string;
            /**
             * Hardware Revision
             * @default null
             */
            hardware_revision: string | null;
            /**
             * Revision Status
             * @default unknown
             * @enum {string}
             */
            revision_status: "unknown" | "known" | "not_applicable";
            /**
             * Configuration Fingerprint
             * @default null
             */
            configuration_fingerprint: string | null;
            /**
             * Identity Evidence Id
             * @default null
             */
            identity_evidence_id: string | null;
            /**
             * Identity Status
             * @default pending
             * @enum {string}
             */
            identity_status: "pending" | "verified";
            /**
             * Status
             * @default unknown
             * @enum {string}
             */
            status: "active" | "discontinued" | "unknown";
        };
        /** CatalogSource */
        CatalogSource: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Record Key */
            record_key: string;
            /**
             * Synthetic
             * @default false
             */
            synthetic: boolean;
            /** Name */
            name: string;
            /** Domain */
            domain: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "manufacturer" | "merchant" | "benchmark" | "manual";
            /**
             * Access Method
             * @enum {string}
             */
            access_method: "manual" | "api" | "web" | "file";
            /**
             * Permission Status
             * @default unknown
             * @enum {string}
             */
            permission_status: "unknown" | "allowed" | "restricted" | "denied";
            /**
             * Permission Evidence
             * @default null
             */
            permission_evidence: string | null;
            /**
             * Terms Checked At
             * @default null
             */
            terms_checked_at: string | null;
            /** Allowed Uses */
            allowed_uses?: ("internal_review" | "public_display" | "automated_fetch" | "excerpt_storage")[];
            /**
             * Requests Per Minute
             * @default null
             */
            requests_per_minute: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    bootstrap_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_current_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_current_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reset_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileSnapshot"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_profile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileSnapshot"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patch_profile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileSnapshot"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_profile_revision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
                revision: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileSnapshot"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    preview_manual_import: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preview"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    stage_manual_import: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJob"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_manual_import: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJob"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    review_manual_import: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJob"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    publish_manual_import: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Published"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_catalog_products: {
        parameters: {
            query?: {
                category?: ("cpu" | "gpu" | "motherboard" | "memory" | "ssd" | "psu" | "case" | "cooler" | "laptop") | null;
                region?: string | null;
                q?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogPage"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_catalog_product: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_catalog_offers: {
        parameters: {
            query?: {
                region?: string | null;
                include_historical?: boolean;
            };
            header?: never;
            path: {
                sku_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferPage"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    quote_catalog_prices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceQuote"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveResponse"];
                };
            };
        };
    };
    get_readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    get_platform_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformStatus"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
